name: melodyku
description: melodyku music service website
version: 0.9.3
homepage: https://www.steryo.melodyku.com
author: Navid shad <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_router: ^2.0.0-alpha+22
  angular_forms: ^2.1.2
  http : ^0.12.0+2
  js: ^0.6.1+1
  socket_io_client: ^0.9.2
  modern_charts: ^0.1.17

dev_dependencies:
  sass_builder: ^2.1.3
  angular_test: ^2.2.0
  build_runner: ^1.7.1
  build_test: ^0.10.3
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
