name: melodyku
description: melodyku music service website
# version: 1.0.0
# homepage: https://www.example.com
# author: Navid shad <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  angular: ^5.0.0-beta
  #angular_components: ^0.9.0-beta
  angular_router: 
  angular_forms:
  http : ^0.11.3+17
  pwa:
  js: ^0.6.0

dev_dependencies:
  angular_test: ^2.0.0-beta
  sass_builder: ^2.0.0
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
