import '../../class/classes.dart';

List<String> patterns = [
  'assets/imgs/patterns/01.jpg',
  'assets/imgs/patterns/02.jpg',
  'assets/imgs/patterns/03.jpg',
  'assets/imgs/patterns/04.jpg',
  'assets/imgs/patterns/05.jpg',
  'assets/imgs/patterns/06.jpg',
  'assets/imgs/patterns/07.jpg',
  'assets/imgs/patterns/08.jpg',
  'assets/imgs/patterns/09.jpg',
  'assets/imgs/patterns/10.png',
  // 'assets/imgs/patterns/11.png',
  // 'assets/imgs/patterns/12.png',
  // 'assets/imgs/patterns/13.png',
  // 'assets/imgs/patterns/14.png',
  // 'assets/imgs/patterns/15.png',
  // 'assets/imgs/patterns/16.png',
  // 'assets/imgs/patterns/17.png',
  // 'assets/imgs/patterns/18.png',
  // 'assets/imgs/patterns/19.png',
  // 'assets/imgs/patterns/22.png',
  // 'assets/imgs/patterns/23.png',
  // 'assets/imgs/patterns/24.png',
  // 'assets/imgs/patterns/25.png',
];